[package]
name = "sovereign_solo_core"
version = "0.1.0"
edition = "2021"
autobins = false

[[bin]]
name = "neural_box_core"
path = "src/main.rs"

[dependencies]
uefi = { version = "0.31", default-features = false }
uefi-raw = { version = "0.7", default-features = false }
ed25519-dalek = { version = "2.2", default-features = false }

[features]
default = []
host-ipc = []
strict-memory-encryption = []

[profile.dev]
panic = "abort"
opt-level = 3

[profile.release]
panic = "abort"
lto = true
opt-level = 3
codegen-units = 1
strip = false
